### ISSUE TITLE
Suggestion to make it avilable as NuGet package.

### ISSUE THREAD

**Issue by Kusnierz-Maciej** [elw00d/consoleframework#39] opened 2017-05-26 10:51 UTC
Hello.
I would like to suggest making NuGet package for easier download and usage.

**Comment by ForNeVeR** [comment] 2017-09-03 03:24
Duplicate of #29.

**Comment by igor-kostromin** [comment] 2017-09-03 07:20
indeed, closing as duplicate

**Closed as completed by igor-kostromin** 2017-09-03 07:20 UTC
